; Note: This file is automatically appended to the php.ini.
; If you update, be sure to restart any nix shells or processes.

date.timezone = America/Los_Angeles
; date.timezone = Europe/London

max_execution_time = -1
memory_limit = 256M

;xdebug.remote_autostart=on
;xdebug.remote_enable=on
;xdebug.remote_mode=req
;xdebug.remote_handler=dbgp
;xdebug.remote_host=localhost
;xdebug.remote_port=9000

xdebug.mode = debug
xdebug.client_host = 127.0.0.1
;# For PhpStorm set below to 9000 (or update IDE's settings).
xdebug.client_port = 9003
xdebug.start_with_request=yes
;xdebug.log="/var/log/nginx/xdebug.log"
;xdebug.idekey = PHPSTORM
xdebug.discover_client_host=false

; Some test suites depend on $_ENV
variables_order=EGPCS

; By default, disable outbound mail
sendmail_path = "/usr/bin/env true"

; Display nicely formatted errors
display_errors = 1

; Support more advanced unit test
runkit.internal_override=1
