/* Auto-generated from CiviCRM-Core-Matrix.matrix.php via update-matrices.php */

String signature(Map item, List keys) {
    def sig = ''
    keys.each { key ->
        sig += '\u0000' + "${item[key]}"
    }
    return sig
}

def expectedItems = [
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php82m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php82m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'backdrop-clean', BKPROF: 'php82m80', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api3'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api4'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-civi'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-crm'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-api3'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-api4'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-civi'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-crm'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php82m80', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-api3'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-api4'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-civi'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-crm'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'drupal-clean', BKPROF: 'php83m80', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'drupal10-clean', BKPROF: 'php82m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'drupal10-clean', BKPROF: 'php82m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'drupal10-clean', BKPROF: 'php82m80', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php82m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php82m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'standalone-clean', BKPROF: 'php82m80', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php82m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php82m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: 'master', BLDTYPE: 'wp-demo', BKPROF: 'php82m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.72', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'standalone-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.71', BLDTYPE: 'wp-demo', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php73m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php73m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php73m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'backdrop-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php73m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api3'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-api4'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-civi'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-crm'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal9-clean', BKPROF: 'php74m57', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'drupal10-clean', BKPROF: 'php81m80', SUITES: 'meta-oddball'],
  [CIVIVER: '5.69', BLDTYPE: 'wp-demo', BKPROF: 'php73m57', SUITES: 'phpunit-core-exts'],
  [CIVIVER: '5.69', BLDTYPE: 'wp-demo', BKPROF: 'php73m57', SUITES: 'phpunit-e2e'],
  [CIVIVER: '5.69', BLDTYPE: 'wp-demo', BKPROF: 'php73m57', SUITES: 'meta-oddball'],
]

def keys = expectedItems[0].keySet().toList()
def expectedSignatures = expectedItems.collect { item ->
    signature(item, keys)
}

combinations.each {item ->
  if (expectedSignatures.contains(signature(item, keys))) {
    result.all = result.all ?: []
    result.all << item
  }
}

return result